---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-alt-options
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/stock-alt-options.git
    targetRevision: main
    path: charts/stock-alt-options
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
