---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: stock-alt-options
images:
  - name: stock-alt-options
    newName: stock-alt-options
    newTag: latest
